version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: maths_solution_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/maths_solution_db?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRY_HOURS: 24
      PORT: 8000
      GIN_MODE: release
      AI_SERVICE_URL: http://ai-service:5000
      AI_SERVICE_TIMEOUT: 30
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      postgres:
        condition: service_healthy
      ai-service:
        condition: service_started
    restart: unless-stopped

  ai-service:
    build:
      context: ../Ai_Model
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MODEL_NAME: gemini-1.5-pro
      HOST: 0.0.0.0
      PORT: 5000
      CACHE_TTL_SECONDS: 600
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  postgres_data:
